steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/mcdonamp/firebase-functions-cloud-build']
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: gcr.io/cloud-builders/npm:node-6.14.4
  args: ['install', 'functions']
- name: 'gcr.io/firebase-functions-cloud-build/firebase'
  args: ['deploy', '--only', 'functions']
  secretEnv: ['FIREBASE_TOKEN']
secrets:
- kmsKeyName: 'projects/firebase-functions-cloud-build/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token'
  secretEnv:
    FIREBASE_TOKEN: CiQA59x8U9n6XkSAjYCRabwznDK8GKSWzEsVHyWvqsKVclApIeASVQAMiuopEmw7LfroQuIApod53KduR5prd90MitYAoXSQeoh/RB4QfNN2kHqrv5iavFcByMrKQqDknCEZiBlFfdNAXsN7fIADgHnmcmJcJm1Qn6GQEx4=