steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/mcdonamp/firebase-functions-cloud-build']
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: gcr.io/cloud-builders/npm
  args: ['install']
- name: 'gcr.io/firebase-functions-cloud-build/firebase'
  args: ['deploy', '--only', 'functions']
  secretEnv: ['FIREBASE_TOKEN']
secrets:
- kmsKeyName: 'projects/firebase-functions-cloud-build/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token'
  secretEnv:
    FIREBASE_TOKEN: 'CiQA59x8U0QfToT45aaVCms/rJG2bdt6jVkMp8aeylaT+47oOMMSVgAMiuopoSgNY0kZyempKoNyARMYouqLItfeS/9jcnBXhb3T0xWL+hMtCahx8yvCD6W4A3E+D1L/2KXbyGfULrI6ii0TJfSew3QAx4UFdAgjm/2u4cxh'